version: 2

project_name: avro

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - main: ./cmd/avro
    binary: avro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X avro_cli/internal/cli.Version={{.Version}}
      - -X avro_cli/internal/cli.Commit={{.Commit}}
      - -X avro_cli/internal/cli.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\(.+\))?\!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^style:"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: avro_cli
  prerelease: auto
  name_template: "v{{ .Version }}"
